# Generated by Django 5.2.6 on 2025-09-06 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('birthday', models.DateField()),
                ('nationality', models.CharField(choices=[('BR', 'Brasil'), ('US', 'Estados Unidos'), ('UK', 'Reino Unido'), ('FR', 'França'), ('JP', 'Japão'), ('KR', 'Coreia do Sul'), ('IN', 'Índia'), ('MX', 'México'), ('IT', 'Itália'), ('DE', 'Alemanha')], max_length=2)),
            ],
        ),
    ]
