# Generated by Django 5.2.6 on 2025-09-06 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0001_initial'),
        ('genres', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('release_date', models.DateField()),
                ('description', models.TextField(max_length=600)),
                ('actors', models.ManyToManyField(to='actors.actor')),
                ('genre', models.ManyToManyField(to='genres.genre')),
            ],
        ),
    ]
